### ISSUE TITLE
Does this violate Spacedrive's license?

### ISSUE THREAD

**Issue by Taywee** [fdncred/nu_plugin_file#1]
Spacedrive is mentioned in the README, and it looks like most of the functional code of this is taken from SpaceDrive, but I don't see any proper attribution.  More importantly, Spacedrive is licensed AGPL, which would require this plugin to also be AGPL.

**Comment by fdncred** [comment]
ya, the license needs to change. i thought i did that already. i have attribution here https://github.com/fdncred/nu_plugin_file/blob/1e95ebc3d65cceb220c676179558ef1c99b79fa5/src/main.rs#L1-L2

i'd appreciate a PR if you have time.
