### ISSUE TITLE
Tagged release versions

### ISSUE THREAD

**Issue by mgttlinger** [fdncred/nu_plugin_file#9]
Hi, I would like to package this plugin in nixpkgs (nixos.org) however targeting commits as versions is always a bit ugly. 

Would it be possible to make tagged releases/or tagged versions for easier packaging?

**Comment by fdncred** [comment]
I'll try to remember with the next release

**Comment by mgttlinger** [comment]
Thanks for considering it. If you add a tag for the current version, I can also package it already.

**Comment by fdncred** [comment]
i remembered, yay me!

**Comment by mgttlinger** [comment]
Thanks
